apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubehub-cluster-01
  region: ap-northeast-1
  version: "1.23"
  
vpc:
  nat:
    gateway: Disable        # other options: HighlyAvailable, Single (default)

managedNodeGroups:
- name: managed-spot-public-ng-01
  spot: true
  privateNetworking: false  # Disbaling auto creation of private subnet
  desiredCapacity: 2
  minSize: 0
  maxSize: 4
  volumeSize: 10
  volumeType: gp2
  instanceTypes:
  - t3a.small
  - t3.small
  ssh:
    allow: true
    publicKeyPath: ec2-access


#Though it is a public node group, nat gateway is not needed.
