apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubehub-cluster-01
  region: ap-northeast-1
  version: "1.22"
nodeGroups:
  - name: managed-ng-2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 10
    volumeType: gp2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3a.small", "t3.small"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 20
    ssh:
      allow: true
      publicKeyPath: ec2-access
